# Generated by Django 4.2.1 on 2023-07-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0003_alter_user_managers_submission_langauge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
